#!/bin/bash
# -----------------------------------------------------------------------------
# package: ultralight provisioning system
# author: Daniel Kovacs <mondomhogynincsen@gmail.com>
# licence: MIT <https://opensource.org/licenses/MIT>
# file-version: 1.4
# file-purpose: aws session helper script
# -----------------------------------------------------------------------------

export AWS_ASSUME_ROLE_INCLUDE_PROFILE=1
export AWS_ASSUME_ROLE=$1
echo "aws-session: assuming role '${AWS_ASSUME_ROLE}' in a sub-shell..."

bash --rcfile /usr/local/bin/aws-assume-role -i
echo "aws-session: sub-shell terminated, session ended"
